version: "3.3"
services:
  graphs_ds:
    container_name: graphs_ds
    image: graphs_ds:latest
    restart: unless-stopped
    build: 
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env    
    volumes:
      - .:/graphs_ds
