version: "3.9"
services:
  java_algorithms:
    build: 
      context: .
      dockerfile: Dockerfile
      shm_size: '1gb'
    image: java_algorithms:latest
    container_name: java_algorithms
    cpus: 0.5
    mem_reservation: '512M'
    mem_limit: '2048M'
    init: true
    network_mode: host
    restart: unless-stopped
    env_file:
      - .env    
    volumes:
      - ${HOME}/.ssh:/tmp/.ssh:ro
      - .:/algorithms
